//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatronMarineServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
