//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatronMarineServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Equipment
    {
        public int SerialNumber { get; set; }
        public string Model { get; set; }
        public string Maker { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> VesselIMO { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public string Fields { get; set; }
        public Nullable<int> TemplateID { get; set; }
    
        public virtual EquipmentTemplates EquipmentTemplates { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Vessel Vessel { get; set; }


        public Dictionary<string, string> FieldsValues
        {
            get {
                if (Fields != null)
                {
                    return JsonConvert.DeserializeObject<Dictionary<string, string>>(Fields);
                }
                else
                    return null;
            }
        }

        public string GetFieldValue(string f)
        {
            if (FieldsValues != null)
            {
                return FieldsValues[f];
            }
            else
                return null;
        }

    }
}
