//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatronMarineServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Equipment
    {
        public int SerialNumber { get; set; }
        public string Model { get; set; }
        public string Maker { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> VesselIMO { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Vessel Vessel { get; set; }
    }
}
