//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatronMarineServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    
    public partial class EquipmentTemplates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentTemplates()
        {
            this.Equipment = new HashSet<Equipment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Fields { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment { get; set; }


        private List<EqField> listFields;

        public List<EqField> FieldsList
        {
            get
            {
                if (Fields != null)
                {
                    listFields = JsonConvert.DeserializeObject<List<EqField>>(Fields);
                }
                else
                    listFields = null;
                return listFields;
            }
        }
        public string FieldsOutput
        {
            get
            {
                string a ="";
                if (Fields != null)
                {
                    foreach (var item in FieldsList)
                    {
                        a += $"{item.Name};";
                    }
                     a = a.Remove(a.Length - 1);
                }
                return a;
            }
        }




    }
}
