//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatronMarineServer.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class ProductFiles
    {
        public int ID { get; set; }
        public string Manual { get; set; }
        public string Picture { get; set; }
        public Nullable<int> ProductID { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Product Product { get; set; }
    }
}
