//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatronMarineServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    public partial class Temp
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public Nullable<int> ObjectID { get; set; }

        public Nullable<System.DateTime> Date { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public string SerializedObject { get; set; }
        public Vessel NewVessel
        {
            get {
                if (Type == "Vessel")
                    return JsonConvert.DeserializeObject<Vessel>(SerializedObject);
                else
                    return null;
            }
        }
        public Equipment NewEquipment
        {
            get
            {
                if (Type == "Equipment")
                    return JsonConvert.DeserializeObject<Equipment>(SerializedObject);
                else
                    return null;
            }
        }

    }
}
