//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatronMarineServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesselAccess
    {
        public int ID { get; set; }
        public Nullable<int> SuperIntendantID { get; set; }
        public Nullable<int> VesselIMO { get; set; }
    
        public virtual User User { get; set; }
        public virtual Vessel Vessel { get; set; }
    }
}
